# Simple email sender using SMTP
$smtpServer = "smtp.gmail.com"
$smtpPort = 587

# Email settings
$to = "sixer0.bk@gmail.com"
$from = "kilotrading@gmail.com"  # You'll need to configure this
$subject = "Trading Simulation Results - Win Rate: 37.7%"

$body = @"
TRADING SIMULATION RESULTS
==========================

Period: 2026-02-06 to 2026-05-07
Initial Capital: $10000
Final Capital: $13735.94
Total P&L: $3735.94 (37.36%)

Total Trades: 329
Win Rate: 37.7% (124 wins / 205 losses)
Avg Win: $307.07 | Avg Loss: $167.52
Largest Win: $528.31 | Largest Loss: $-261.12

Best Coin: ETH
Worst Coin: DOGE
Max Drawdown: 0%

---
Generated by Kilo Trading Agent System
"@

# Check if Send-MailMessage is available
try {
    # Try using Send-MailMessage (requires SMTP configuration)
    $cred = Get-Credential -Message "Enter SMTP credentials to send email"
    if ($cred) {
        Send-MailMessage -SmtpServer $smtpServer -Port $smtpPort -UseSsl -Credential $cred -From $from -To $to -Subject $subject -Body $body -BodyAsHtml:$false
        Write-Host "Email sent successfully!" -ForegroundColor Green
    }
} catch {
    Write-Host "Email sending failed: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "Email content saved for manual sending:" -ForegroundColor Yellow
    Write-Host "To: $to"
    Write-Host "Subject: $subject"
    Write-Host ""
    Write-Host $body
}