#!/usr/bin/env python3
"""
DOCX Example 01: Basic Document Creation
Creates a simple document with headings and paragraphs.
"""

from docx import Document
from docx.shared import Pt

def create_basic_document():
    doc = Document()
    doc.add_heading('Document Processing Report', 0)
    doc.add_paragraph('Generated by Kilo Agent')

    doc.add_heading('Introduction', level=1)
    doc.add_paragraph('This report demonstrates basic document creation.')

    doc.add_heading('Key Findings', level=1)
    findings = [
        'Document automation increases productivity',
        'Consistent formatting improves readability',
        'Template-based creation ensures compliance'
    ]
    for finding in findings:
        doc.add_paragraph(finding, style='List Bullet')

    return doc

if __name__ == "__main__":
    doc = create_basic_document()
    doc.save("example_01_basic.docx")
    print("[OK] Created: example_01_basic.docx")